language: go
go:
- 1.7
cache:
  directories:
  - vendor
install:
- go get -u github.com/kardianos/govendor
- govendor sync
script:
- govendor vet +local
- govendor test +local
before_deploy:
- GOOS=linux GOARCH=amd64 govendor build -o kubemerge_linux_amd64
- GOOS=darwin GOARCH=amd64 govendor build -o kubemerge_darwin_amd64
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Yb3BVKnyaKpsD/YbI8Me3t1kktnlttFwCJmt6cnCjfvg3Sp7lN0yKhw46AHGAjWxdhw+yRHPN80o+FY70v2wWP+Hez3kj+BX0UxDEh5Izr5m1WVEssmvnLJ2hSjLbcUfBMDyrvE3poSXYA6ITLqxQBAqIa+hZfFUNIyq91SraXMasMop4NmFyZNnH3UPioKPE5t5ZHaIFkOQOlsEt65UFwYKP9z5S1TYBUkiBvuYvJz+BVq7cEbxg4is3fK5Kj6Nahzj1XySBHhQiNMeAFeYvqoLemdhmpEGwb6TlJ3nuxW5flDGBifYuAfzqgSBGXCNSLO/TxEQr+SuqeGv5o4u+SvvhqaXmvKjEU1lWcruXnJ4Mm+lwWNkfjihuikvZE2KmRFO8G0mqDzojdNjATkd1OQYO9q6F8QrMPVu+q0OuOG4c3g/HMNIfo5clU/T3x8cFDeVuYfrfF1Pk1EnacWQKi7SDZiyBkEaPg2fX+hbt25TJQEnDKs2Dq4ZPskY6BQesH5aRsm7ABmRASSel7NPZGUHbP4owanPMKaP06ylfD7AG2zd684H7vVmwqSccibgxWFWDvrVUaAOyLr7pWY8hUtNTUsmey2vDvlxUAxHc1LlVMKHewgiAYB/E0z4vMS3aim+VLu/hxRC+pZehDohtYXYsAHDoEIyYsd99Ek514c=
  file:
  - kubemerge_linux_amd64
  - kubemerge_darwin_amd64
  on:
    tags: true
    repo: nextrevision/kubemerge
